// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANFaQE6u3Mjo7hFUZdap4-kRIB94-8cLc',
    appId: '1:132329320998:web:26815999a111fd26f26ce7',
    messagingSenderId: '132329320998',
    projectId: 'dapur-aja',
    authDomain: 'dapur-aja.firebaseapp.com',
    storageBucket: 'dapur-aja.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEvpSBk-E4YJLPJT1F7OYoTf4jCF-xbzk',
    appId: '1:132329320998:android:510c96d26113f0e5f26ce7',
    messagingSenderId: '132329320998',
    projectId: 'dapur-aja',
    storageBucket: 'dapur-aja.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmvqPHLLHV8dJyz0DYLpYT-CuRkRhfh-E',
    appId: '1:132329320998:ios:7351a973a01faf64f26ce7',
    messagingSenderId: '132329320998',
    projectId: 'dapur-aja',
    storageBucket: 'dapur-aja.appspot.com',
    iosClientId: '132329320998-7offteea8h1sh7f7k72voe4dvma0gmac.apps.googleusercontent.com',
    iosBundleId: 'com.oksama.dapur',
  );
}
